// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaizesApi.Data;

#nullable disable

namespace RaizesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424010606_PrimeiroMigration")]
    partial class PrimeiroMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RaizesApi.CanalPedido", b =>
                {
                    b.Property<int>("IdCanalPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_canal_pedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCanalPedido"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdCanalPedido");

                    b.ToTable("canal_pedido");
                });

            modelBuilder.Entity("RaizesApi.CategoriaProduto", b =>
                {
                    b.Property<int>("IdCategoriaProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_produto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoriaProduto"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdCategoriaProduto");

                    b.ToTable("categoria_produto");
                });

            modelBuilder.Entity("RaizesApi.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("documento");

                    b.Property<bool>("Fidelizado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("fidelizado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int>("PontosFidelidade")
                        .HasColumnType("int")
                        .HasColumnName("pontos_fidelidade");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.HasKey("IdCliente");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("RaizesApi.Colaborador", b =>
                {
                    b.Property<int>("IdColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_colaborador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdColaborador"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("documento");

                    b.Property<int>("IdUnidade")
                        .HasColumnType("int")
                        .HasColumnName("id_unidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario");

                    b.HasKey("IdColaborador");

                    b.ToTable("colaborador");
                });

            modelBuilder.Entity("RaizesApi.ItemPedido", b =>
                {
                    b.Property<int>("IdItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_item_pedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdItemPedido"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProdutoUnidade")
                        .HasColumnType("int")
                        .HasColumnName("id_produto_unidade");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.HasKey("IdItemPedido");

                    b.ToTable("item_pedido");
                });

            modelBuilder.Entity("RaizesApi.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<int>("IdCanalPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_canal_pedido");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdStatusPagamento")
                        .HasColumnType("int")
                        .HasColumnName("id_status_pagamento");

                    b.Property<int>("IdStatusPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_status_pedido");

                    b.Property<int>("IdUnidade")
                        .HasColumnType("int")
                        .HasColumnName("id_unidade");

                    b.HasKey("IdPedido");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("RaizesApi.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<int>("IdCategoriaProduto")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_produto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("IdProduto");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("RaizesApi.ProdutoUnidade", b =>
                {
                    b.Property<int>("IdProdutoUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produto_unidade");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdutoUnidade"));

                    b.Property<int>("Estoque")
                        .HasColumnType("int")
                        .HasColumnName("estoque");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("id_produto");

                    b.Property<int>("IdUnidade")
                        .HasColumnType("int")
                        .HasColumnName("id_unidade");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco");

                    b.HasKey("IdProdutoUnidade");

                    b.ToTable("produto_unidade");
                });

            modelBuilder.Entity("RaizesApi.StatusPagamento", b =>
                {
                    b.Property<int>("IdStatusPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_status_pagamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdStatusPagamento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdStatusPagamento");

                    b.ToTable("status_pagamento");
                });

            modelBuilder.Entity("RaizesApi.StatusPedido", b =>
                {
                    b.Property<int>("IdStatusPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_status_pedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdStatusPedido"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdStatusPedido");

                    b.ToTable("status_pedido");
                });

            modelBuilder.Entity("RaizesApi.Unidade", b =>
                {
                    b.Property<int>("IdUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidade");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUnidade"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("IdUnidade");

                    b.ToTable("unidade");
                });
#pragma warning restore 612, 618
        }
    }
}
